version: '2'

services:
  app:
    image: 'clicker-image'
    build:
      context: .
    ports:
      - 8080:8080
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/clicker
      - SPRING_DATASOURCE_USERNAME=clicker
      - SPRING_DATASOURCE_PASSWORD=clicker
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=clicker
      - POSTGRES_PASSWORD=clicker